// @sanity/icons v5 exposes each icon as its own subpath import.
export { AddUserIcon } from '@sanity/icons/AddUser'
export { CalendarIcon } from '@sanity/icons/Calendar'
export { CogIcon } from '@sanity/icons/Cog'
export { DiamondIcon } from '@sanity/icons/Diamond'
export { DownloadIcon } from '@sanity/icons/Download'
export { EnvelopeIcon } from '@sanity/icons/Envelope'
export { HomeIcon } from '@sanity/icons/Home'
export { ImagesIcon } from '@sanity/icons/Images'
export { RocketIcon } from '@sanity/icons/Rocket'
export { StarIcon } from '@sanity/icons/Star'
export { TagIcon } from '@sanity/icons/Tag'
export { UploadIcon } from '@sanity/icons/Upload'
export { UserIcon } from '@sanity/icons/User'
export { UsersIcon } from '@sanity/icons/Users'
export { WarningOutlineIcon } from '@sanity/icons/WarningOutline'
